#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

# Kiểm tra BRANCH_NAME không rỗng và không ở trạng thái detached HEAD
if [ ! -z "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "HEAD" ] && [ "$SKIP_PREPARE_COMMIT_MSG" != 1 ]; then

  PREFIX_PATTERN='[A-Z]{1,5}-[0-9]{1,6}'  # Tìm pattern dạng R-001
  
  if [[ $BRANCH_NAME =~ $PREFIX_PATTERN ]]; then
    PREFIX=${BASH_REMATCH[0]}  # Lấy phần match đầu tiên
    echo "🔍 PREFIX detected: $PREFIX"  # Debug log kiểm tra
    
    PREFIX_IN_COMMIT=$(grep -c "$PREFIX: " "$1")

    # Nếu PREFIX tồn tại trong branch name và chưa có trong commit message
    if [[ -n "$PREFIX" ]] && [[ $PREFIX_IN_COMMIT -eq 0 ]]; then
      sed -i.bak -e "1s~^~$PREFIX: ~" "$1"
      echo "✅ Added PREFIX '$PREFIX' to commit message."
    else
      echo "⚠️ PREFIX '$PREFIX' already exists in commit message. Skipping."
    fi
  else
    echo "❌ No PREFIX found in branch name: $BRANCH_NAME"
  fi

fi

